
(module info (lib "infotab.ss" "setup")
  (define name "mzfam")
  (define blurb '("A file alteration monitor"))
  (define primary-file "fam-task.ss")
  (define doc.txt "html/mzfam.html")
  (define html-docs '("html"))
  (define categories '(io))
  (define version "2.1")
  (define release-notes '("Minor bug fixes. Recommended for all 2.0 users."))
  (define required-core-version "4.2"))
